### PR TITLE
TOOLS-2707: add go1.15 support

### PR DESCRIPTION
**Pull request by huan-Mongo**

### CODE REVIEW

**Comment by tfogo** [comment]
@huan-Mongo can you run a full evg patch? Just want to check all the hosts support 1.15

**Comment by huan-Mongo** [comment]
@tfogo Yes! I ran it in Mongo-tools PR. I will run one here as well.

**Comment by huan-Mongo** [comment]
@tfogo I reran the test against all variants. Sorry it took so long, the last time I ran it and it crashed evergreen somehow. The evergreen team asked me to hold on until they fixed the issue. 
So far there is no test failure related to the change.

**Comment by huan-Mongo** [comment]
@varsha804 Maybe you can now take a look as well? Thanks!

**Comment by tfogo** [comment]
Yeah, there were passing tasks on the variants that have system failures too so I think it's safe to say 1.15 is correctly supported. LGTM!

**Review by tfogo — APPROVED** [review]

**Review by varsha804 — APPROVED** [review]
Cool, LGTM!

**Pull request merged**
